name: Build, Push and Scan Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.slanedrv }}
        password: ${{ secrets.dckr_pat_z6tqyh48eddYk_FGOOynI8kGdQQ }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.slanedrv }}/myapp:latest
        cache-from: type=registry,ref=${{ secrets.slanedrv }}/myapp:buildcache
        cache-to: type=inline

    - name: Scan the Docker image with Docker Scout
      uses: docker/scout-action@v1
      with:
        severity: 'high'
        fail-on: 'high'
        username: ${{ secrets.slanedrv }}
        password: ${{ secrets.dckr_pat_z6tqyh48eddYk_FGOOynI8kGdQQ }}
        image: ${{ secrets.slanedrv }}/myapp:latest

    - name: Push the Docker image to GitHub Packages
      if: success()
      run: |
        echo ${{ secrets.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 }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag ${{ secrets.slanedrv }}/myapp:latest ghcr.io/${{ github.repository_owner }}/myapp:latest
        docker push ghcr.io/${{ github.repository_owner }}/myapp:latest
