jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        ACTIONS_STEP_DEBUG: true  # Включение подробного логирования для этого шага

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: ghcr.io/${{ github.repository }}/myapp:latest
        push: true
      env:
        ACTIONS_STEP_DEBUG: true  # Включение подробного логирования для этого шага

    - name: Check docker metadata
      run: docker images --digests
