name: GHAction example  

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
      
    steps:
      - 
        name: Check out the source_repo
        uses: actions/checkout@v4
      
      - 
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/example
          flavor: latest=false
          tags: |
            type=sha,priority=100,format=short
            type=semver,priority=200,pattern={{version}}
 

      - 
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - 
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false  # Поменяйте push на false для предварительной сборки
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/example:cache 
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/example:cache  
          tags: ${{ steps.meta.outputs.tags }}
          
      - 
        name: Scan image with Docker Scout
        uses: docker/scout-action@v1
        with:
          image: ghcr.io/${{ github.repository_owner }}/example:latest
          fail-on-severity: critical,high

      -
        name: Push image to GitHub Container Registry
        if: success()  # Этот шаг выполняется, если предыдущий шаг не обнаружил уязвимостей
        run: docker push ghcr.io/${{ github.repository_owner }}/example:latest
