name: GHAction example  

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub and GHCR
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out the source_repo
        uses: actions/checkout@v4
      
      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/example
            ghcr.io/${{ github.repository_owner }}/example
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}   

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/example:cache 
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/example:cache,mode=max 
          tags: ${{ steps.meta.outputs.tags }}

      - name: Scan image with Docker Scout
        uses: docker/scout-action@v1
        with:
          image: ${{ steps.meta.outputs.tags }}

      - name: Push to DockerHub and GHCR
        if: steps.scout.outputs.critical == '0' && steps.scout.outputs.high == '0'
        run: |
          echo "Pushing image to DockerHub and GHCR"
          docker push ${{ steps.meta.outputs.tags }}
